2019-04-13 15:14:41,884 invalid literal for int() with base 10: 'lkjh01'
Traceback (most recent call last):
  File "/files/univer/python/course2/math_projects/kateryna/bin/front.py", line 81, in _fill_monitor_tree
    date_from = list(map(int, self._date_from.get().split('-')))
ValueError: invalid literal for int() with base 10: 'lkjh01'
2019-04-13 16:24:22,015 unknown url type: 'fjgdkf'
Traceback (most recent call last):
  File "/files/univer/python/course2/math_projects/kateryna/bin/front.py", line 223, in _add_site
    urlopen(link)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 511, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'fjgdkf'
2019-04-13 16:24:29,305 unknown url type: 'link.com'
Traceback (most recent call last):
  File "/files/univer/python/course2/math_projects/kateryna/bin/front.py", line 223, in _add_site
    urlopen(link)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 511, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'link.com'
